export const actions ={
    INCREMENT_COUNTER:'INCREMENT_COUNTER',
    DECREMENT_COUNTER:'DECREMENT_COUNTER',
    ADD_COUNTER:'ADD_COUNTER',
    SUB_COUNTER:'SUB_COUNTER',
    RESET_COUNTER:'RESET_COUNTER'
}